---
- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - import_tasks: yum-lock-wait.yaml
    - name: install Docker
      yum:
       name: docker
       state: present
       update_cache: true
    - import_tasks: yum-lock-wait.yaml
    - name: start Docker
      service:
       name: docker
       state: started
    - import_tasks: yum-lock-wait.yaml
    - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      sysctl:
       name: net.bridge.bridge-nf-call-ip6tables
       value: 1
       state: present
    - import_tasks: yum-lock-wait.yaml
    - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
       name: net.bridge.bridge-nf-call-iptables
       value: 1
       state: present

    - name: add Kubernetes' YUM repository
      yum_repository:
       name: Kubernetes
       description: Kubernetes YUM repository
       baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
       gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
       gpgcheck: yes

    - name: install kubelet
      yum:
        name: kubelet-1.14.0
        state: present
        update_cache: true

    - name: install kubeadm
      yum:
        name: kubeadm-1.14.0
        state: present

    - name: start kubelet
      service:
       name: kubelet
       enabled: yes
       state: started
       
